name: Deploy React App to Azure

on:
  push:
    branches:
      - master

permissions: # Place at the root level of the workflow file
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure using OIDC
        uses: azure/login@v1 # Make sure this uses 'v1' or the latest version
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: oidc

      - name: Log in to Azure Container Registry
        env:
          REGISTRY_NAME: andremorad
        run: |
          az acr login --name $REGISTRY_NAME

      - name: Build and push Docker image
        env:
          REGISTRY_NAME: andremorad.azurecr.io
          IMAGE_NAME: react-app
        run: |
          docker build -t $REGISTRY_NAME/$IMAGE_NAME:${{ github.sha }} .
          docker push $REGISTRY_NAME/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "andre-morad-portfolio"
          images: "andremorad.azurecr.io/react-app:${{ github.sha }}"
