name: Deploy React App to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure using environment variables
        uses: azure/login@v2 # Updated to latest
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Log in to Azure Container Registry
        env:
          REGISTRY_NAME: andremorad
        run: |
          echo ${{ secrets.AZURE_CLIENT_SECRET }} | docker login $REGISTRY_NAME.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

      - name: Build and push Docker image
        env:
          REGISTRY_NAME: andremorad.azurecr.io
          IMAGE_NAME: react-app
        run: |
          docker build -t $REGISTRY_NAME/$IMAGE_NAME:${{ github.sha }} .
          docker push $REGISTRY_NAME/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "andre-morad-portfolio" # Your Azure Web App name
          images: "andremorad.azurecr.io/react-app:${{ github.sha }}"
